### ISSUE TITLE
dhis 2 replace all my app in the page of it

### ISSUE THREAD

**Issue by adirzoari** [hisptz/dhis2-touch-v2#1]
hello,
i downloaded it and just run it, suddenly all my apps project old & new replace to be this the page of this app, means any app i run "ionic run serve" i got exactly same page of your app
![dhis](https://cloud.githubusercontent.com/assets/20258998/20566648/7a3509dc-b19e-11e6-9665-7f89d385b0d0.jpg)
 what can i do?
it's never happen to me.

**Comment by chingalo** [comment]
Dear 

I have check your concerning. I have also faced same issue after upgrade by ionic to Version 2.1.13 and resolve by just clear my browser cache
